### ISSUE TITLE
Research how to use NPU on rk3588 CPU

### ISSUE THREAD

**Issue by cvetaevvitaliy** [Military-Vehicle-Detection/buildroot-rk3588#5]
Reference:

https://wiki.t-firefly.com/en/Core-3588J/usage_npu.html

Latest YoloV5 file for convert to rknn format for Rockchip NPU
Need to convert .pt file to rknn format
https://drive.google.com/drive/folders/1-xryH0eSDzheDWSjgkPuZV5yG_PaIiE5?usp=share_link

**Comment by vkulyeshov** [comment]
Make research
