### ISSUE TITLE
Adjust CI/DI

### ISSUE THREAD

**Issue by vkulyeshov** [Military-Vehicle-Detection/buildroot-rk3588#7]
- Update CI pipelines
- Create release on merge action to master branch
- Add release notes
- Add reviewers

**Comment by olexam** [comment]
master branch is protected, the rules:

1. Require a pull request before merging
2. Only particular users (cvetaevvitaliy, olexa.m) could bypass the rule

**Comment by olexam** [comment]
The release creates on merge PR to the master branch.

The communication message for the release is taken from the merge message.

The merge message is parsed for version numbering control.

If no version numbering control sequences are not specified in the message version bumps a patch number like 1.0.4 -> 1.0.5
To specify the exact version to release you need to create, add a version in format **1.1.1** in the merge message
To increase a minor number like 1.0.5 -> 1.1.0 add a **(MINOR)** in the merge message
To increase a major number like 1.2.3 -> 2.0.0 add a **(MAJOR)** in the merge message.
